before:
  hooks:
  - go mod download

builds:
- id: eventhorizon
  main: ./cmd/eventhorizon/main.go
  binary: bin/eventhorizon
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
  files:
  - LICENSE
  - README.md
  - samples/**/*
  - install/**/*

checksum:
  name_template: checksums.txt

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc

dockers:
- goos: linux
  goarch: amd64
  dockerfile: Dockerfile
  binaries:
  - bin/eventhorizon
  image_templates:
  - "acesso/eventhorizon:latest"
  - "acesso/eventhorizon:{{ .Tag }}"
  - "acesso/eventhorizon:v{{ .Major }}"
  - "acesso/eventhorizon:v{{ .Major }}.{{ .Minor }}"
  extra_files:
  - LICENSE
  - README.md
  - samples
  - install
