version: '3'

services:
  fluentd:
    image: fluent/fluentd:v1.5-1
    command: [ "fluentd", "-c", "/fluentd/etc/default.conf" ]
    volumes:
    - ./samples/fluentd.conf:/fluentd/etc/default.conf
    - fluentd-sock:/tmp
    ports:
    - 24224:24224
    - "24224:24224/udp"

  eventhorizon:
    image: acesso/eventhorizon
    command: [ "/opt/acesso/bin/eventhorizon" ]
    environment:
    - EVENTHORIZON_MODE=standalone
    - EVENTHORIZON_NAME=eventhorizon
    - EVENTHORIZON_STANDALONE_CONFIG=/opt/acesso/samples/standalone/stdout.yml
    - EVENTHORIZON_LOGGING_LEVEL=debug
    - EVENTHORIZON_LOGGING_PRETTY=true
    ports:
    - 1257:1257
    volumes:
    - fluentd-sock:/tmp
    depends_on:
    - fluentd
    restart: always

volumes:
  fluentd-sock:
