apiVersion: eventhorizon.acesso.io/v1alpha2
kind: EventHorizon
metadata:
  name: eventhorizon
spec:
  labels:
    field1: value1
    field2: value2
  queue:
    backlog: 8192
    maxRetry: 13
    retryWait: 500
    maxRetryWait: 60000
  metrics:
    port: 1258
    path: /metrics
  transport:
    type: http
    http:
      port: 1257
      useStatusCodeOK: true
  encoder:
    type: map
  output:
    type: fluentd
    fluentd:
      socketPath: /tmp/fluentd.sock
      network: unix
      timeout: 3s
      writeTimeout: 0s
      bufferLimit: 8192
      retryWait: 500
      maxRetryWait: 60000
      maxRetry: 13
      tagPrefix: ""
      async: false
      subSecondPrecision: false
      requestAck: false
  # validator:
  #   allowedTypes:
  #   - io.request.grpc
  #   - io.request.rpc
  #   - io.request.http
  #   - io.event.consumer
  #   - io.event.producer
  #   allowedSources: []
