apiVersion: v1
kind: List
items:

- apiVersion: eventhorizon.acesso.io/v1alpha1
  kind: Singularity
  metadata:
    name: eventhorizon
  spec:
    transport:
      name: http
      http:
        port: 1257
        useStatusCodeOK: true # force success response code to be 200 (fortio benchmark only understands HTTP 200)
      # nats:
      #   server: http://localhost:4222
      #   subject: eventhorizon
    validation: true
    metrics:
      enabled: true
      path: /metrics
      port: 1258
    backlog: 8192
    maxRetry: 25
    retryWait: 500
    maxRetryWait: 65000

- apiVersion: eventhorizon.acesso.io/v1alpha1
  kind: CloudEventOutput
  metadata:
    name: stdout
  spec:
    type: stdout

- apiVersion: eventhorizon.acesso.io/v1alpha1
  kind: CloudEventHandler
  metadata:
    name: default
  spec:
    subjects:
    - eventhorizon
    labels:
      field1: value1
      field2: value2
    encoder: map
    output: stdout

- apiVersion: eventhorizon.acesso.io/v1alpha1
  kind: CloudEventValidator
  metadata:
    name: default
  spec:
    handlers:
    - default
    priority: -1
    allowedTypes:
    - io.request.grpc
    - io.request.rpc
    - io.request.http
    - io.event.consumer
    - io.event.producer
    allowedSources: []
