apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: eventhorizon
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventhorizon
rules:
- apiGroups: ["eventhorizon.acesso.io"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eventhorizon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eventhorizon
subjects:
  - kind: ServiceAccount
    name: eventhorizon
    namespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: eventhorizon
data:
  fluentd.conf: |
    <source>
      @type unix
      path /opt/acesso/run/fluentd.sock
    </source>

    <match *.**>
      @type stdout
    </match>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: eventhorizon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventhorizon
  template:
    metadata:
      labels:
        app: eventhorizon
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "1258"
        prometheus.io/path: /metrics
    spec:
      serviceAccountName: eventhorizon
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: eventhorizon
        image: acesso/eventhorizon
        command: [ "/opt/acesso/bin/eventhorizon" ]
        env:
        - name: EVENTHORIZON_NAME
          value: kube-system/eventhorizon
        ports:
        - containerPort: 1257
        volumeMounts:
        - name: run
          mountPath: /opt/acesso/run
        readinessProbe:
          httpGet:
            path: /healthz
            port: 1257
          initialDelaySeconds: 5
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 1257
          initialDelaySeconds: 5
          periodSeconds: 3
      - name: fluentd
        image: fluent/fluentd:v1.7-1
        command: [ "fluentd", "-c", "/opt/acesso/config/fluentd.conf" ]
        volumeMounts:
        - name: config
          mountPath: /opt/acesso/config
        - name: run
          mountPath: /opt/acesso/run
---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: eventhorizon
spec:
  ports:
  - port: 1257
    name: http
  selector:
    app: eventhorizon
---
