apiVersion: eventhorizon.acesso.io/v1alpha1
kind: CloudEventHandler
metadata:
  name: default
spec:
  subjects:
  - kube-system/eventhorizon
  labels:
    field1: value1
    field2: value2
  encoder: map
  output: fluentd
