apiVersion: eventhorizon.acesso.io/v1alpha1
kind: CloudEventOutput
metadata:
  name: fluentd
spec:
  type: fluentd
  fluentd:
    socketPath: /opt/acesso/run/fluentd.sock
    network: unix
    timeout: 0s
    writeTimeout: 3s
    bufferLimit: 8192
    retryWait: 500
    maxRetryWait: 60000
    async: false
    subSecondPrecision: false
    tagPrefix: ""
