apiVersion: eventhorizon.acesso.io/v1alpha1
kind: CloudEventValidator
metadata:
  name: default
spec:
  handlers:
  - default
  priority: -1
  allowedTypes:
  - io.request.grpc
  - io.request.rpc
  - io.request.http
  - io.event.consumer
  - io.event.producer
  allowedSources: []
