apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cloudeventhandlers.eventhorizon.acesso.io
spec:
  group: eventhorizon.acesso.io
  names:
    kind: CloudEventHandler
    plural: cloudeventhandlers
    singular: cloudeventhandler
    shortNames:
    - ceh
    categories:
    - acesso-io
    - eventhorizon-acesso-io
  scope: Cluster
  version: v1alpha1
