apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eventhorizons.eventhorizon.acesso.io
spec:
  group: eventhorizon.acesso.io
  names:
    kind: EventHorizon
    plural: eventhorizons
    singular: eventhorizon
    shortNames:
    - eh
    categories:
    - acesso-io
    - eventhorizon-acesso-io
  scope: Namespaced
  version: v1alpha2
